{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "webapp-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "webapp-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      scheme: https
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify }}
{{- end }}
