{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "webapp-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.service.port }}
      targetPort: webhook
      protocol: TCP
{{- end }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-operator.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "webapp-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
