---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-myapp-example-com-v1alpha1-webapp
  failurePolicy: Fail
  name: mwebapp-v1alpha1.kb.io
  rules:
  - apiGroups:
    - myapp.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-myapp-example-com-v1beta1-webapp
  failurePolicy: Fail
  name: mwebapp-v1beta1.kb.io
  rules:
  - apiGroups:
    - myapp.example.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webapps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-myapp-example-com-v1alpha1-webapp
  failurePolicy: Fail
  name: vwebapp-v1alpha1.kb.io
  rules:
  - apiGroups:
    - myapp.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-myapp-example-com-v1beta1-webapp
  failurePolicy: Fail
  name: vwebapp-v1beta1.kb.io
  rules:
  - apiGroups:
    - myapp.example.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webapps
  sideEffects: None
